alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias logout='pkill -KILL -u $USER'
alias nvim='cd $NVIM_CONFIG'
alias n='cd $NVIM_CONFIG; vim'
alias v='vim'
alias dot='cd $DOT_FILES'
alias conf='cd $XDG_CONFIG_HOME'
alias scripts='cd ~/.scripts'
alias td='todo'
alias tdd='tdr'
alias lg='lazygit'
alias open='xdg-open'
alias tss='gnome-screenshot -a'
alias settings='xfce4-display-settings & disown'
alias react='cd ~/dev/react'
alias dev='cd ~/dev'
alias natas='cd ~/hack/otw/natas/'
alias 201='cd ~/dev/cf/js/201/curriculum'
alias 301='cd ~/dev/cf/js/301/curriculum'
alias play='cd ~/dev/playground'
alias mongodb='sudo systemctl start mongod'
alias mongodb='sudo systemctl status mongod'
alias bye=goodbye.sh
alias exmon=ex_mon_only_on.sh
alias setex=ex_mon_on.sh
alias updatecc=update_code_fellows_git_repos.sh
alias luamake=$NVIM_CONFIG/language-servers/lua-language-server/3rd/luamake/luamake
alias lmp=list_man_pack.sh
alias mkfile=mkfile.sh
alias freeport=freeport.sh
