lastupdatecheck: 0
recentrepos:
- /home/natkiypie/.dotfiles
- /home/natkiypie/test
- /home/natkiypie/dev/cf/js/301/curriculum
- /home/natkiypie/dev/react
- /home/natkiypie/dev/react/redux/t3
- /home/natkiypie/temp
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: true
