require('plugins')
require('keybindings')
require('options')
require('treesitter-config')
require('telescope-config')
require('comment-config')
require('colors')
require('bufferline-config')
require('autopairs-config')
require('blankline-config')
require('lsp-config')
-- Temp - open telescope when entering vim in workspace
vim.cmd('autocmd VimEnter * Telescope find_files')
