###############################################################
# Selection Mark
###############################################################
show_selection_mark = false

###############################################################
# Search Modes
###############################################################
[search-modes]
"<empty>" = "fuzzy path"
"/" = "regex name"
"g/" = "regex content"

###############################################################
# Special Paths
###############################################################
[special-paths]
"*/node_modules" = "no-enter"
"*/node_modules" = "hide"
"*/build" = "no-enter"
"*/build" = "hide"
"*/package-lock.json" = "no-enter"
"*/package-lock.json" = "hide"

###############################################################
# Pager
###############################################################
[[verbs]]
name = "view"
invocation = "view"
key = "ctrl-v"
execution = "$EDITOR -R -M {file}"
leave_broot = false

###############################################################
# Verbs and Shortcuts
###############################################################

# Editing

[[verbs]]
invocation = "edit"
shortcut = "e"
execution = "$EDITOR +{line} {file}"
leave_broot = false

[[verbs]]
invocation = "touch {subpath}"
execution = "touch {directory}/{subpath}"
leave_broot = false

# Navigation

[[verbs]]
key = "ctrl-h"
execution = ":toggle_hidden"

[[verbs]]
invocation = "home"
execution = ":focus ~"

[[verbs]]
key = "left"
execution = ":parent"

[[verbs]]
key = "right"
execution = ":focus"

[[verbs]]
key = "shift-h"
execution = ":parent"

[[verbs]]
key = "shift-l"
execution = ":focus"

[[verbs]]
key = "shift-j"
execution = ":line_down"

[[verbs]]
key = "shift-k"
execution = ":line_up"

[[verbs]]
key = "ctrl-d"
execution = ":page_down"

[[verbs]]
key = "ctrl-u"
execution = ":page_up"

# Git

[[verbs]]
key = "ctrl-s"
execution = ":toggle_git_status"

[[verbs]]
key = "ctrl-f"
execution = ":toggle_git_file_info"

###############################################################
# Skin
###############################################################

[skin]
default = "none none"
file =  "none none"
flag_label = "none none"
flag_value = "none none Bold"
input = "none none"
status_normal = "black none"
status_job = "none none"
status_italic = "none none"
status_bold = "none none"
status_code = "none none"
status_ellipsis = "black none"
directory = "rgb(84, 124, 153) none bold"

# tree = "rgb(89, 73, 101) none"
# file = "gray(21) none"
# directory = "rgb(255, 152, 0) none bold"
# exe = "rgb(17, 164, 181) none"
# link = "Magenta none"
# pruning = "rgb(89, 73, 101) none Italic"
# perm__ = "gray(5) None"
# perm_r = "ansi(94) None"
# perm_w = "ansi(132) None"
# perm_x = "ansi(65) None"
# owner = "gray(12) none"
# group = "gray(12) none"
# selected_line = "none gray(3)"
# char_match = "yellow none"
# file_error = "Red none"
# flag_label = "gray(16) none"
# flag_value = "rgb(255, 152, 0) none bold"
# input = "White none"
# status_error = "Red gray(2)"
# status_job = "ansi(220) gray(5)"
# status_normal = "gray(20) gray(3)"
# status_italic = "rgb(255, 152, 0) None"
# status_bold = "rgb(255, 152, 0) None bold"
# status_code = "ansi(229) gray(5)"
# status_ellipsis = "gray(19) gray(1)"
# scrollbar_track = "rgb(80, 50, 0) none"
# scrollbar_thumb = "rgb(255, 187, 0) none"
# help_paragraph = "gray(20) none"
# help_bold = "rgb(255, 187, 0) none bold"
# help_italic = "Magenta rgb(30, 30, 40) italic"
# help_code = "gray(21) gray(3)"
# help_headers = "rgb(255, 187, 0) none"
