# USED IN: ~/.dotfiles/config/.config/nvim/lua/scripts/terminals/broot.lua"
[[verbs]]
invocation = "terminal"
key = "shift-l"
execution = ":print_path"
apply_to = "file"

[[verbs]]
invocation = "terminal"
key = "enter"
execution = ":print_path"
apply_to = "file"
