-- fun! s:ToggleMouse()
--     if !exists("s:old_mouse")
--         let s:old_mouse = "a"
--     endif
--     if &mouse == ""
--         let &mouse = s:old_mouse
--         echo "Mouse is for Vim (" . &mouse . ")"
--     else
--         let s:old_mouse = &mouse
--         let &mouse=""
--         echo "Mouse is for terminal"
--     endif
-- endfunction

-- toggle()
-- local M = {}
-- 
-- function M.toggle()
--   for _, win in ipairs(vim.api.nvim_list_wins()) do
--     local config = vim.api.nvim_win_get_config(win)
--     if config.relative ~= "" then
--       vim.api.nvim_win_close(win, false)
--       vim.cmd('bd')
--     else
--       vim.cmd('bd')
--     end end
-- end
-- 
-- return M
