alias logout='pkill -KILL -u natkiypie'
alias n='cd ~/.dotfiles/config/.config/nvim ; vim'
alias v='vim'
alias dot='cd ~/.dotfiles'
alias conf='cd ~/.dotfiles/config/.config'
alias scripts='cd ~/.dotfiles/scripts/.scripts'
alias td='todo'
alias tdd='tdr'
alias lg='lazygit'
alias open='xdg-open'
alias tss='gnome-screenshot -a'
alias settings='xfce4-display-settings & disown'
alias react='cd ~/dev/react'
alias dev='cd ~/dev'
alias natas='cd ~/hack/otw/natas/'
alias 201='cd ~/dev/cf/js/201/curriculum'
alias 301='cd ~/dev/cf/js/301/curriculum'
alias play='cd ~/dev/playground'
alias mongodb='sudo systemctl start mongod'
alias mongodb='sudo systemctl status mongod'
alias bye=goodbye.sh
alias exmon=ex_mon_only_on.sh
alias setex=ex_mon_on.sh
alias updatecc=update_code_fellows_git_repos.sh
alias luamake=/home/natkiypie/.dotfiles/nvim/lua-language-server/3rd/luamake/luamake
